### ISSUE TITLE
[BUG] Flame with grpc backend hangs for larger model like resnet50

### ISSUE THREAD

**Issue by gauravgadewar36** [cisco-open/flame#225]
**Describe the bug**
When job is deployed with p2p backend it hangs for larger model like ResNet50 (98 MB) and even for smaller one's like MobileNetV2 (14 MB). Aggregator is not able to send global model parameters to the trainers even the initial one before beginning of any training round. Due to this job keeps on running without any failure.

**To Reproduce**

1] Change the model in the medmnist example with ResNet50.
2] Deploy the job with backend as p2p.

**Expected behavior**
Aggregator should have sent global model parameters to all the trainers.

**Additional context**
Error Logs below:

2022-09-08 22:39:27,183 | top_aggregator.py:111 | DEBUG | MainThread | _aggregate_weights | waiting to receive data from b4bc6d48269d32625db218eab86f7a033a3f6140
2022-09-08 22:39:27,195 | p2p.py:402 | DEBUG | Thread-2 | _unicast_task | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flame/backend/p2p.py", line 399, in _unicast_task
    await self.send_chunks(end_id, channel.name(), data)
  File "/usr/local/lib/python3.9/site-packages/flame/backend/p2p.py", line 425, in send_chunks
    await svr_writer.write(msg)
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 141, in write
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi", line 147, in _send_message
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi", line 98, in execute_batch
grpc._cython.cygrpc.ExecuteBatchError: Failed "execute_batch": (<grpc._cython.cygrpc.SendInitialMetadataOperation object at 0x7f17b8313e00>, <grpc._cython.cygrpc.SendMessageOperation object at 0x7f18abce7630>)

2022-09-08 22:39:27,195 | p2p.py:403 | DEBUG | Thread-2 | _unicast_task | An exception of type ExecuteBatchError occurred

**Comment by myungjin** [comment]
@gauravgadewar36 Thanks for letting us know this bug. Can you post a link for MobileNetV2 that you used or code so that we can test?

**Comment by gauravratnakar256** [comment]
@myungjin  PFA MobileNetV2 code this works perfectly with mqtt backend but hangs for p2p.

Ran the job with 2 clients and for 2 rounds

[medmnist.zip](https://github.com/cisco-open/flame/files/9559654/medmnist.zip)

**Comment by myungjin** [comment]
@gauravratnakar256 Thanks for sharing the code; we will investigate.

**Comment by myungjin** [comment]
@gauravgadewar36 Please run the test and reopen there is any further issue.
